# Generated by Django 4.2 on 2025-05-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('feliz', '😊 Feliz'), ('neutral', '😐 Neutral'), ('triste', '😢 Triste'), ('enojado', '😠 Enojado'), ('ansioso', '😰 Ansioso')], max_length=10),
        ),
    ]
